---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: suculent/platformio-docker-build
    commands:
      - bash script/build-tester.sh
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: output/quicksilver*.hex
      overwrite: true
    when:
      event:
        - tag
