---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: hanfer/docker-gcc-arm-none-eabi:latest
    commands:
      - bash QUICKSILVER/script/build-tester.sh
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: output/quicksilver*.hex
      prerelease: true
      title: latest
      overwrite: true
      draft: true
    when:
      event:
        - tag
