---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: hanfer/docker-platformio
    commands:
      - bash script/build-tester.sh
  - name: publish-github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: output/quicksilver*.hex
      overwrite: true
    when:
      event:
        - tag
  - name: publish-hanfer
    image: appleboy/drone-scp
    settings:
      host: hanfer.org
      user: drone
      password:
        from_secret: ssh_password
      source:
        - output/index.html
        - output/quicksilver*.hex
      target: /mnt/hanfer/public/quicksilver
      strip_components: 1
    when:
      branch:
        - develop
      event:
        - push
