#pragma once

#include "target.h"

//  CONDITIONAL SELECTION OF DEFINES BASED ON USER SELECTED UART FOR SERIAL RX, TARGET MCU, AND TARGET DEFINED USART ALTERNATE MAPPING PINS
#ifdef F4
#define USART1_PA10PA9 USART_PORT(1, PIN_A10, PIN_A9)
#define USART1_PB7PB6 USART_PORT(1, PIN_B7, PIN_B6)
#define USART1_PB7PA9 USART_PORT(1, PIN_B7, PIN_A9)
#define USART2_PA3PA2 USART_PORT(2, PIN_A3, PIN_A2)
#define USART3_PB11PB10 USART_PORT(3, PIN_B11, PIN_B10)
#define USART3_PC11PC10 USART_PORT(3, PIN_C11, PIN_C10)
#define USART4_PA1PA0 USART_PORT(4, PIN_A1, PIN_A0)
#define USART5_PD2PC12 USART_PORT(5, PIN_D2, PIN_C12)
#define USART6_PC7PC6 USART_PORT(6, PIN_C7, PIN_C6)
#endif

#define USART_IDENT(channel) USART_PORT##channel
#define USART_PORT(channel, rx_pin, tx_pin) USART_IDENT(channel),

typedef enum {
  USART_PORT_INVALID,
  USART_PORTS
      USART_PORTS_MAX,
} usart_ports_t;

#undef USART_PORT
