#pragma once

#include "target.h"

//  CONDITIONAL SELECTION OF DEFINES BASED ON USER SELECTED UART FOR SERIAL RX, TARGET MCU, AND TARGET DEFINED USART ALTERNATE MAPPING PINS
#ifdef F4

#define USART1_PA10PA9 USART_PORT(1, A, 10, 9)
#define USART2_PA3PA2 USART_PORT(2, A, 3, 2)
#define USART3_PB11PB10 USART_PORT(3, B, 11, 10)
#define USART3_PC11PC10 USART_PORT(3, C, 11, 10)
#define USART4_PA1PA0 USART_PORT(4, A, 1, 0)
#define USART6_PC7PC6 USART_PORT(6, C, 7, 6)

#endif

/* TODO
#ifdef F0
#if defined(UART_1)
#ifdef USART1_PA3PA2
#define SERIAL_RX_USART USART1
#define SERIAL_RX_SPEKBIND_BINDTOOL_PIN GPIO_Pin_2
#define SERIAL_RX_SPEKBIND_RX_PIN GPIO_Pin_3
#define SERIAL_RX_PIN GPIO_Pin_3
#define SERIAL_RX_PORT GPIOA
#define SERIAL_RX_SOURCE GPIO_PinSource3
#define SERIAL_RX_CHANNEL GPIO_AF_1
#define SERIAL_USART_IRQ USART1_IRQn
#endif
#ifdef USART1_SDA
#define SERIAL_RX_USART USART1
#define SERIAL_RX_SPEKBIND_BINDTOOL_PIN GPIO_Pin_3
#define SERIAL_RX_PIN GPIO_Pin_14
#define SERIAL_RX_PORT GPIOA
#define SERIAL_RX_SOURCE GPIO_PinSource14
#define SERIAL_RX_CHANNEL GPIO_AF_1
#define SERIAL_USART_IRQ USART1_IRQn
#endif
#endif
#endif
*/