#include "config.h"
#include "config_helper.h"

#define iFlightF745AIOv2

// PORTS
#define SPI_PORTS   \
  SPI1_PA5PA6PA7    \
  SPI2_PB13PB14PB15 \
  SPI3_PC10PC11PC12 \
  SPI4_PE2PE5PE6

#define USART_PORTS \
  USART1_PA10PA9    \
  USART2_PA3PA2     \
  USART3_PB11PB10   \
  USART4_PA1PA0     \
  USART6_PC7PC6     \
  USART7_PE7PE8     \
  USART8_PE0PE1

// LEDS
#define LED_NUMBER 1
#define LED1PIN PIN_C13
#define LED2_INVERT

#define BUZZER_PIN PIN_D2
#define BUZZER_INVERT

// GYRO
#define GYRO_TYPE BMI270
#define GYRO_SPI_PORT SPI_PORT1
#define GYRO_NSS PIN_A4
#define GYRO_INT PIN_D0
#define GYRO_ID_1 0x24

// RADIO
#define SOFTSPI_NONE
#ifdef SERIAL_RX
#define RX_USART USART_PORT1
#endif

// OSD
#define ENABLE_OSD
#define MAX7456_SPI_PORT SPI_PORT4
#define MAX7456_NSS PIN_E4

// VOLTAGE DIVIDER
#define DISABLE_ADC

#define BATTERYPIN PIN_C3
#define BATTERY_ADC_CHANNEL LL_ADC_CHANNEL_1

#ifndef VOLTAGE_DIVIDER_R1
#define VOLTAGE_DIVIDER_R1 10000
#endif

#ifndef VOLTAGE_DIVIDER_R2
#define VOLTAGE_DIVIDER_R2 1000
#endif

#ifndef ADC_REF_VOLTAGE
#define ADC_REF_VOLTAGE 3.3
#endif

// MOTOR PINS
// S3_OUT
#define MOTOR_PIN0 MOTOR_PIN_PB4
// S4_OUT
#define MOTOR_PIN1 MOTOR_PIN_PB5
// S1_OUT
#define MOTOR_PIN2 MOTOR_PIN_PB0
// S2_OUT
#define MOTOR_PIN3 MOTOR_PIN_PB1
